#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# ENVIRONMENTAL VARIABLES ---------------------------------

#export ANACONDA_HOME=/Users/alexandonian/anaconda3
export ANACONDA_HOME=${HOME}/anaconda3
export PATH=${ANACONDA_HOME}/bin:$PATH

export SUBL_HOME=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin
export PATH=$PATH:${SUBL_HOME}

export HOME_BIN=${HOME}/bin
export PATH=$PATH:${HOME_BIN}

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export MESHLAB_HOME=/Applications/meshlab.app/Contents/MacOS
export PATH=$PATH:${MESHLAB_HOME}

export NODE_PATH=/usr/local/lib/node_modules

#export FREESURFER_HOME=/Applications/freesurfer
#source $FREESURFER_HOME/SetUpFreeSurfer.sh
export PYTEST_ADDOPTS="-W ignore::DeprecationWarning"
export ADB_PATH="${HOME}/Library/Android/sdk/platform-tools"
export PATH=${PATH}:${ADB_PATH}
